### ISSUE TITLE
"@prismicio/client does not provide default export" error deploying to Netlfiy

### ISSUE THREAD

**Issue by wonder95** [prismicio/prismic-client#256]
### Versions

- @prismicio/client: 6.5.1
- node: 16.16.0 (Netlify version)

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

- Create static Astro site (no SSR) with Prismic using `@prismicio/client`
- Push to Github repository
- Create site on Netlify, deploying from GitHub repo
- Start deployment

### What is expected?

Successful site deployment

### What is actually happening?

I get the following console error on Netlify
```
3:04:15 PM:  error   The requested module '@prismicio/client' does not provide an export named 'default'
3:04:15 PM:     at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
3:04:15 PM:     at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
3:04:15 PM:     at async Promise.all (index 0)
3:04:15 PM:     at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
3:04:15 PM:     at async generatePages (file:///opt/build/repo/node_modules/astro/dist/core/build/generate.js:70:20)
3:04:15 PM:     at async staticBuild (file:///opt/build/repo/node_modules/astro/dist/core/build/static-build.js:68:7)
3:04:15 PM:     at async AstroBuilder.build (file:///opt/build/repo/node_modules/astro/dist/core/build/index.js:83:5)
3:04:15 PM:     at async AstroBuilder.run (file:///opt/build/repo/node_modules/astro/dist/core/build/index.js:123:7)
3:04:15 PM:     at async build (file:///opt/build/repo/node_modules/astro/dist/core/build/index.js:22:3)
3:04:15 PM:     at async runCommand (file:///opt/build/repo/node_modules/astro/dist/cli/index.js:138:14)
```

Here is my `package.json`:
```
{
  "name": "@example/basics",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview"
  },
  "devDependencies": {
    "@astrojs/image": "^0.3.4",
    "@astrojs/tailwind": "^0.2.1",
    "@astrojs/vue": "^0.1.4",
    "astro": "^1.0.3",
    "vue": "^3.2.33"
  },
  "dependencies": {
    "@prismicio/client": "^6.5.1",
    "@prismicio/helpers": "^2.3.1",
    "@prismicio/richtext": "^2.1.0"
  }
}
```

**Comment by angeloashmore** [comment]
Hi @wonder95, could you provide an code snippet showing how you are using `@prismicio/client` in your project? Thanks! 🙂

**Comment by wonder95** [comment]
@angeloashmore It turns out it was my error. In following some examples I was importing like so
```
import Prismic from '@prismicio/client`
```
instead of 
```
import * as prismic from '@prismicio/client'
```
Once I fixed that, the problem went away.

**Comment by angeloashmore** [comment]
Awesome! Glad to hear you found a fix. 🙂

If you come any examples from Prismic that use the default export, please let us know and we'll get them updated. 👍
