### ISSUE TITLE
Use of `rehype-parse` causes CommonJS builds to fail

### ISSUE THREAD

**Issue by strmer15** [prismicio/prismic-client#345]
### Versions

- @prismicio/client: 7.7.4
- node: 20.15.1

### Reproduction

Get the latest version of `@prismicio/client` and use it in a CommonJS build with Webpack.

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

Use `@prismicio/client` 7.7.x in a CommonJS build with Webpack.

### What is expected?

I can use `@prismicio/client` in a CommonJS Webpack build without any errors.

### What is actually happening?

It's throwing `ERR_REQUIRE_ESM` when trying to load `rehype-parse`. The `rehype-parse` package is ESM only, so by including it this package has essentially become ESM only.

```
/home/cplummer/work/beethoven/node_modules/.pnpm/@prismicio+client@7.7.4/node_modules/@prismicio/client/dist/helpers/unstable_htmlAsRichText.cjs:121
undefined
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/cplummer/work/beethoven/node_modules/.pnpm/rehype-parse@9.0.0/node_modules/rehype-parse/index.js from /home/cplummer/work/beethoven/node_modules/.pnpm/@prismicio+client@7.7.4/node_modules/@prismicio/client/dist/helpers/unstable_htmlAsRichText.cjs not supported.
Instead change the require of index.js in /home/cplummer/work/beethoven/node_modules/.pnpm/@prismicio+client@7.7.4/node_modules/@prismicio/client/dist/helpers/unstable_htmlAsRichText.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.newLoader [as .js] (/home/cplummer/work/beethoven/node_modules/.pnpm/pirates@4.0.6/node_modules/pirates/lib/index.js:121:7)
    at Module.<anonymous> (/home/cplummer/work/beethoven/node_modules/.pnpm/@prismicio+client@7.7.4/node_modules/@prismicio/client/dist/helpers/unstable_htmlAsRichText.cjs:3:21)
    at Object.newLoader [as .js] (/home/cplummer/work/beethoven/node_modules/.pnpm/pirates@4.0.6/node_modules/pirates/lib/index.js:121:7) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.15.1
```

**Comment by lihbr** [comment]
Hi @strmer15, thanks for contributing and bringing this issue to our attention.

I'm curious if you can share more about your webpack setup? Which framework you're using, meta-framework if any, etc.

We'll release a fix for this tomorrow, in the meantime, pinning `@prismicio/client` to `~7.6.0` should keep you rolling.

**Comment by strmer15** [comment]
Thanks for getting back to me! We're using Webpack 5 and Typescript 5.5 with React 18, just a custom config that has `swc-loader` to transform TS / JS along with some other typical CSS / SVG / GraphQL loaders for bundling. It also uses SSR to build pages that are SEO compatible, so there's both a server and client bundle to support that. I don't think I can share the full config, but let me know if you want other info about how we're doing this.

**Comment by lihbr** [comment]
Hey @strmer15, just keeping you in the loop.

We opened #346 to address this issue. It'll probably be published between today and Monday ☺️

**Comment by lihbr** [comment]
Hey @strmer15, just letting you know we're aligning on a strategy to fix this issue durably so we might need a few extra days to release this fix (I'm expecting Wednesday, definitely this week) to prevent confusion and additional back-and-forth and between the solutions we're envisaging (non-exhaustively: inlining ESM-only dependencies to CJS, exporting the new utilities we introduced to a dedicated package)

Is it alright for you to remain on `~7.6.0` until then?

**Comment by strmer15** [comment]
Hey @lihbr ! No problem, there's no rush here on our part - we're good being on 7.6.0 for a while. Definitely make sure you take all the time you need to come up with the right fix, thanks!

**Comment by lihbr** [comment]
Hi @strmer15, this should be fixed with `@prismicio/client` latest release.

```
npm install @prismicio/client@latest
```

Thanks for your patience! 🙏 Feel free to reopen if you still experience the same trouble.
